import { ProjectProps } from '@/app/interfaces/interfaces';

export const projects: ProjectProps[] = [
    {
        href: '/projects/1',
        category: 'Территории',
        title: 'Нагатинский Затон',
        year: '2017',
        locationValue: 'Москва',
        imageSrc: '/project-1.png',
        imageAlt: 'Метро Нагатинский Затон',
    },
    {
        href: '/projects/2',
        category: 'Реконструкция и реставрация',
        title: 'Стадион Луи II в Монако',
        year: '2025',
        locationValue: 'Монако',
        imageSrc: '/project-1.png',
        imageAlt: 'Стадион Луи II',
    },
    {
        href: '/projects/3',
        category: 'Территории',
        title: 'Светлоград под Калининградом',
        year: '2024',
        locationValue: 'Калининград',
        imageSrc: '/project-1.png',
        imageAlt: 'Светлоград',
    },
    {
        href: '/projects/4',
        category: 'Реконструкция и реставрация',
        title: 'Skyborn gardens в Абу-Даби',
        year: '2023',
        locationValue: 'Абу-Даби',
        imageSrc: '/project-1.png',
        imageAlt: 'Skyborn gardens, Reem Island',
    },
    {
        href: '/projects/5',
        category: 'Частная архитектура',
        title: 'Ферсман Тауэр',
        year: '2021',
        locationValue: 'Москва',
        imageSrc: '/project-1.png',
        imageAlt: 'Ферсман Тауэр',
    },
    {
        href: '/projects/6',
        category: 'Сакральное и общественное',
        title: 'Центр культуры РФ в Сингапуре',
        year: '2020',
        locationValue: 'Сингапур',
        imageSrc: '/project-1.png',
        imageAlt: 'Центр культуры РФ при Храме Успения Божьей Матери',
    },
    {
        href: '/projects/7',
        category: 'Сакральное и общественное',
        title: 'Храм святого пророка Илии',
        year: '2023',
        locationValue: 'Москва',
        imageSrc: '/project-1.png',
        imageAlt: 'Храм святого пропрока Божьего Илии',
    },
    {
        href: '/projects/8',
        category: 'Сакральное и общественное',
        title: 'Пансионат для детей "Ковчег"',
        year: '2018',
        locationValue: 'Москва',
        imageSrc: '/project-1.png',
        imageAlt: 'Храм святого пропрока Божьего Илии',
    },
    {
        href: '/projects/9',
        category: 'Сакральное и общественное',
        title: 'Офис Семейный Доктор',
        year: '2023',
        locationValue: 'Москва',
        imageSrc: '/project-1.png',
        imageAlt: 'Офис Семейный Доктор',
    },
    {
        href: '/projects/10',
        category: 'Дизнайн и арт-объекты',
        title: 'Тангейзер в Зарядье',
        year: '2025',
        locationValue: 'Москва',
        imageSrc: '/project-1.png',
        imageAlt: 'Тангейзер в Зарядье',
    }
];